Vous devez implémenter deux classes :
• PhoneBook
◦ Représente le répertoire.
◦ Contient un tableau de contacts.
◦ Peut enregistrer 8 contacts maximum. Si l’utilisateur tente d’ajouter un 9ème
contact, remplacez le plus ancien par celui-ci.
◦ Notez que l’allocation dynamique est interdite.
• Contact
◦ Représente un contact dans le répertoire.

Dans votre code, l’objet répertoire doit être une instance de la classe PhoneBook.
Même chose pour les objets contacts, qui doivent être chacun une instance de la classe
Contact. Vous êtes libre de concevoir vos classes comme vous le sentez. Par contre, ayez
en tête que ce qui est toujours utilisé dans une classe est privé, et que ce qui peut l’être
en dehors est public.
